export {
  ASSETS,
  BRAND_COLORS,
  FEATURE_BENEFITS,
  FOOTER_LINKS,
} from "./brand";
export {
  ANIMATION_BOUNCE_LOOP_START_INDEX,
  ANIMATION_FPS,
  ANIMATION_FRAME_PATHS,
  ANIMATION_TOTAL_FRAMES,
} from "./animation";
