import {
  Archive,
  ArrowBendUpLeft,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowSquareOut,
  ArrowUp,
  ArrowUpRight,
  ArrowsClockwise,
  ArrowsInSimple,
  ArrowsLeftRight,
  ArrowsOutSimple,
  Bell,
  BellRinging,
  Brain,
  Briefcase,
  Buildings,
  Calendar,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  ChartBar,
  ChartLineUp,
  ChatCircle,
  ChatsCircle,
  ChatText,
  Check,
  CheckCircle,
  CheckFat,
  CheckSquare,
  Circle,
  CircleNotch,
  Clock,
  Command,
  Compass,
  Copy,
  CreditCard,
  CurrencyDollar,
  Diamond,
  DotsThree,
  DotsThreeVertical,
  DownloadSimple,
  Envelope,
  Eye,
  EyeSlash,
  FileArchive,
  FileText,
  FileVideo,
  FilmSlate,
  Funnel,
  Gear,
  Globe,
  IconContext,
  Info,
  Lifebuoy,
  Lightning,
  LinkSimple,
  List,
  Lock,
  MagicWand,
  MagnifyingGlass,
  Megaphone,
  Minus,
  Moon,
  NotePencil,
  PaperPlaneTilt,
  Pause,
  Pen,
  PencilSimple,
  Play,
  PlayCircle,
  Plug,
  Plus,
  Question,
  RocketLaunch,
  Robot,
  Shield,
  ShieldCheck,
  SidebarSimple,
  SignOut,
  SlidersHorizontal,
  Sparkle,
  SpeakerHigh,
  SpeakerLow,
  SpeakerSlash,
  SquaresFour,
  Sun,
  Target,
  Trash,
  Tray,
  TrendUp,
  Trophy,
  UploadSimple,
  User,
  UserCheck,
  UserCircle,
  UserCircleCheck,
  UserPlus,
  Users,
  UsersThree,
  VideoCamera,
  Warning,
  WarningCircle,
  X,
  XCircle,
} from "@phosphor-icons/react";
import type { Icon as AppIcon, IconProps, IconWeight } from "@phosphor-icons/react";
import { forwardRef } from "react";

export type { AppIcon, IconProps, IconWeight };
export { IconContext };

export const Link2 = forwardRef<SVGSVGElement, IconProps>(function Link2({ weight = "bold", ...props }, ref) {
  return <LinkSimple ref={ref} {...props} weight={weight} />;
});

export {
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Bell,
  Brain,
  Briefcase,
  Check,
  CheckFat,
  CheckSquare,
  Circle,
  Clock,
  Command,
  Compass,
  Copy,
  CreditCard,
  Diamond,
  Eye,
  EyeSlash,
  FileArchive,
  FileText,
  FileVideo,
  Globe,
  Info,
  Lock,
  Megaphone,
  Minus,
  Moon,
  Pause,
  Pen,
  Play,
  Plug,
  Plus,
  Shield,
  ShieldCheck,
  SlidersHorizontal,
  Sun,
  Target,
  Trophy,
  User,
  UserCheck,
  UserPlus,
  Users,
  X,
};

export {
  ChartBar as BarChart3,
  BellRinging as BellDot,
  Robot as Bot,
  Briefcase as BriefcaseBusiness,
  Buildings as Building2,
  Calendar as CalendarDays,
  ChartLineUp as ChartNoAxesCombined,
  CheckCircle as CheckCircle2,
  Check as CheckIcon,
  CaretDown as ChevronDown,
  CaretDown as ChevronDownIcon,
  CaretLeft as ChevronLeft,
  CaretRight as ChevronRight,
  CaretRight as ChevronRightIcon,
  CaretUp as ChevronUpIcon,
  WarningCircle as CircleAlert,
  CheckCircle as CircleCheck,
  CheckCircle as CircleCheckIcon,
  Question as CircleHelp,
  PlayCircle as CirclePlay,
  XCircle as CircleX,
  FilmSlate as Clapperboard,
  Clock as Clock3,
  CurrencyDollar as DollarSign,
  DownloadSimple as Download,
  DotsThree as Ellipsis,
  ArrowSquareOut as ExternalLink,
  NotePencil as FilePenLine,
  Funnel as Filter,
  Globe as Globe2,
  Tray as Inbox,
  Info as InfoIcon,
  SquaresFour as LayoutDashboard,
  Lifebuoy as LifeBuoy,
  CircleNotch as Loader2,
  CircleNotch as Loader2Icon,
  CircleNotch as LoaderCircle,
  SignOut as LogOut,
  ArrowsOutSimple as Maximize2,
  List as Menu,
  ChatCircle as MessageCircle,
  ChatText as MessageSquare,
  ChatsCircle as MessagesSquare,
  ArrowsInSimple as Minimize2,
  DotsThree as MoreHorizontal,
  DotsThreeVertical as MoreVertical,
  XCircle as OctagonXIcon,
  SidebarSimple as PanelLeftClose,
  SidebarSimple as PanelLeftOpen,
  Pen as PenLine,
  PencilSimple as Pencil,
  ArrowsClockwise as RefreshCw,
  ArrowsLeftRight as Replace,
  ArrowBendUpLeft as Reply,
  RocketLaunch as Rocket,
  MagnifyingGlass as Search,
  PaperPlaneTilt as Send,
  Gear as Settings,
  Sparkle as Sparkles,
  VideoCamera as SquarePlay,
  TrendUp as TrendingUp,
  Warning as TriangleAlert,
  Warning as TriangleAlertIcon,
  UploadSimple as Upload,
  UserCircle as UserRound,
  UserCircleCheck as UserRoundCheck,
  UsersThree as UsersRound,
  VideoCamera as Video,
  SpeakerLow as Volume1,
  SpeakerHigh as Volume2,
  SpeakerSlash as VolumeX,
  MagicWand as WandSparkles,
  X as XIcon,
  WarningCircle as AlertCircle,
  Warning as AlertTriangle,
  ChartLineUp as Activity,
  ArrowDown as ArrowDownIcon,
  Command as CommandIcon,
  EyeSlash as EyeOff,
  Funnel as FilterIcon,
  Tray as InboxIcon,
  Envelope as Mail,
  Trash as Trash2,
  Lightning as Zap,
};
