export {
  ASSETS,
  BRAND_COLORS,
  FEATURE_BENEFITS,
  FOOTER_COLUMNS,
  FOOTER_COPYRIGHT,
  FOOTER_SOCIAL_LINKS,
  FOOTER_TAGLINE,
} from "./brand";
export {
  ANIMATION_BOUNCE_LOOP_START_INDEX,
  ANIMATION_BOUNCE_START_SECONDS,
  ANIMATION_FPS,
  ANIMATION_TOTAL_FRAMES,
  ANIMATION_VIDEO_SRC,
} from "./animation";
