"use client";

import { useRouter } from "next/navigation";
import {
  ArrowLeft,
  ArrowRight,
  BarChart3,
  Check,
  CirclePlay,
  Sparkles,
  TrendingUp,
  Upload,
  UserPlus,
} from "lucide-react";
import { useEffect, useLayoutEffect, useState } from "react";
import { HeroBadge } from "@/components/onboarding/HeroBadge";
import { OnboardingCard } from "@/components/onboarding/OnboardingCard";
import { OnboardingChrome } from "@/components/onboarding/OnboardingChrome";
import { Button } from "@/components/ui/Button";
import { applyStoredTheme } from "@/hooks/useThemeMode";
import { apiFetch, bootstrapOrganization } from "@/lib/api";
import {
  onboardingHref,
  strategyHref,
} from "./steps";

const CAMPAIGN_TYPE_OPTIONS = [
  {
    id: "personalized_outreach",
    title: "Personalized Outreach",
    description: "AI videos personalized for each prospect.",
    bestFor: [
      "Lead generation",
      "Direct conversations",
      "Highest conversion potential",
    ],
    tag: "Generated by AI",
    icon: UserPlus,
  },
  {
    id: "ai_video_ad",
    title: "AI Video Ad",
    description: "One AI-generated video used across many prospects.",
    bestFor: ["Awareness", "Traffic", "Lead generation at scale"],
    tag: "Create Instantly • Studio",
    icon: CirclePlay,
  },
  {
    id: "uploaded_video",
    title: "Uploaded Video Campaign",
    description: "Use your own video across your campaigns.",
    bestFor: ["Existing content", "Brand consistency", "Faster launch"],
    tag: "Upload • Studio",
    icon: Upload,
  },
] as const;

const VIDEO_ADVANTAGE_STATS = [
  { value: "40%", label: "Higher response rates", icon: TrendingUp },
  { value: "3-4x", label: "More engagement", icon: BarChart3 },
  { value: "2-5x", label: "More conversions", icon: BarChart3 },
] as const;

type CampaignType = (typeof CAMPAIGN_TYPE_OPTIONS)[number]["id"];

type StrategyResponse = {
  id: string;
  orgId: string;
  campaignType: CampaignType | null;
};

function CampaignTypeActions({
  canContinue,
  isSaving,
  onBack,
  onContinue,
}: {
  canContinue: boolean;
  isSaving: boolean;
  onBack: () => void;
  onContinue: () => void;
}) {
  return (
    <div className="pointer-events-none fixed inset-x-0 bottom-7 z-30 flex items-center justify-between px-6 sm:px-10">
      <Button
        type="button"
        variant="secondary"
        onClick={onBack}
        className="pointer-events-auto h-13 px-7 text-base"
      >
        <ArrowLeft className="size-5" aria-hidden />
        Back
      </Button>
      <Button
        type="button"
        variant="brand"
        disabled={!canContinue || isSaving}
        onClick={onContinue}
        className="pointer-events-auto h-13 px-8 text-base sm:px-10"
      >
        {isSaving ? "Saving..." : "Continue to next step"}
        <ArrowRight className="size-5" aria-hidden />
      </Button>
    </div>
  );
}

export default function CampaignTypeClient() {
  useLayoutEffect(() => {
    applyStoredTheme();
  }, []);

  const router = useRouter();
  const [orgId, setOrgId] = useState<string | null>(null);
  const [selectedType, setSelectedType] = useState<CampaignType | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;

    async function loadStrategy() {
      try {
        const bootstrap = await bootstrapOrganization("LeadReacher");
        if (cancelled) return;

        setOrgId(bootstrap.orgId);
        const strategy = await apiFetch<StrategyResponse>(
          `/strategy/${bootstrap.orgId}`,
        );
        if (cancelled) return;

        setSelectedType(strategy.campaignType);
      } catch (loadError) {
        if (!cancelled) {
          setError(
            loadError instanceof Error
              ? loadError.message
              : "Unable to load your campaign settings.",
          );
        }
      } finally {
        if (!cancelled) {
          setIsLoading(false);
        }
      }
    }

    void loadStrategy();
    return () => {
      cancelled = true;
    };
  }, []);

  async function handleContinue() {
    if (!selectedType || !orgId || isSaving) {
      return;
    }

    setIsSaving(true);
    setError(null);
    try {
      await apiFetch<StrategyResponse>(`/strategy/${orgId}/campaign-type`, {
        method: "PATCH",
        body: JSON.stringify({ campaignType: selectedType }),
      });
      router.push(onboardingHref("video-decision"));
    } catch (saveError) {
      setError(
        saveError instanceof Error
          ? saveError.message
          : "Unable to save your campaign type.",
      );
    } finally {
      setIsSaving(false);
    }
  }

  return (
    <div className="onboarding-page relative flex h-dvh min-h-dvh w-full flex-col overflow-y-auto">
      <OnboardingChrome activeStep="campaign-type" />

      <main className="mx-auto flex w-full max-w-6xl flex-1 flex-col justify-center px-5 pb-28 pt-28 lg:pt-34">
        <div className="mx-auto flex max-w-2xl flex-col items-center text-center">
          <HeroBadge icon={<Sparkles className="size-7" />} />
          <h1 className="mt-5 text-3xl font-bold tracking-tight text-onboarding-ink sm:text-4xl dark:text-onboarding-neutral-0">
            Choose your campaign type
          </h1>
          <p className="mt-4 max-w-lg text-base leading-7 text-onboarding-neutral-600 dark:text-onboarding-neutral-400">
            We&apos;ll recommend the best content, channels, and strategy based on your selection.
          </p>
        </div>

        {error ? (
          <p
            role="alert"
            className="mx-auto mt-6 w-full max-w-4xl rounded-onboarding bg-onboarding-error-50 px-4 py-3 text-sm text-onboarding-error-900 ring-1 ring-onboarding-error-500/20 dark:bg-onboarding-error-900 dark:text-onboarding-error-50"
          >
            {error}
          </p>
        ) : null}

        <OnboardingCard className="mx-auto mt-8 w-full max-w-4xl px-5 py-5 sm:px-6">
          <div className="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between">
            <div className="flex min-w-0 items-start gap-3">
              <Sparkles className="mt-0.5 size-5 shrink-0 text-onboarding-purple-500" aria-hidden />
              <div>
                <p className="text-xs font-bold tracking-wide text-onboarding-purple-600 uppercase dark:text-onboarding-purple-200">
                  Video Advantage
                </p>
                <p className="mt-1 text-sm leading-6 text-onboarding-neutral-600 dark:text-onboarding-neutral-400">
                  Video helps capture attention, increase engagement, and improve campaign performance.
                </p>
              </div>
            </div>
            <div className="grid grid-cols-3 gap-3 sm:gap-7">
              {VIDEO_ADVANTAGE_STATS.map((stat) => {
                const Icon = stat.icon;
                return (
                  <div key={stat.label} className="min-w-0 text-center sm:text-left">
                    <div className="flex items-center justify-center gap-1.5 sm:justify-start">
                      <Icon className="size-4 text-onboarding-purple-500" aria-hidden />
                      <p className="text-lg font-bold text-onboarding-purple-600 dark:text-onboarding-purple-200">{stat.value}</p>
                    </div>
                    <p className="mt-0.5 text-xs leading-snug text-onboarding-neutral-500 dark:text-onboarding-neutral-400">
                      {stat.label}
                    </p>
                  </div>
                );
              })}
            </div>
          </div>
        </OnboardingCard>

        <div className="mx-auto mt-6 grid w-full max-w-4xl gap-4 md:grid-cols-3">
          {CAMPAIGN_TYPE_OPTIONS.map((option) => {
            const Icon = option.icon;
            const isSelected = selectedType === option.id;

            return (
              <button
                key={option.id}
                type="button"
                onClick={() => setSelectedType(option.id)}
                className={`app-card app-card--interactive relative flex min-h-80 flex-col overflow-hidden text-left focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-onboarding-purple-300 ${
                  isSelected ? "app-card--selected" : ""
                }`}
                aria-pressed={isSelected}
              >
                {isSelected ? (
                  <span className="absolute top-4 right-4 inline-flex size-7 items-center justify-center rounded-onboarding-pill bg-onboarding-purple-500 text-white shadow-onboarding-button">
                    <Check className="size-4 stroke-[2.5]" aria-hidden />
                  </span>
                ) : null}
                <div className="flex flex-1 flex-col px-5 pb-5 pt-8">
                  <Icon className="size-6 text-onboarding-purple-500" aria-hidden />
                  <h2 className="mt-4 text-lg font-bold text-onboarding-ink dark:text-onboarding-neutral-0">{option.title}</h2>
                  <p className="mt-2 text-sm leading-6 text-onboarding-neutral-600 dark:text-onboarding-neutral-400">{option.description}</p>
                  <p className="mt-5 text-xs font-semibold tracking-wide text-onboarding-neutral-500 uppercase">
                    Best for
                  </p>
                  <ul className="mt-2 space-y-2 text-sm text-onboarding-neutral-700 dark:text-onboarding-neutral-300">
                    {option.bestFor.map((item) => (
                      <li key={item} className="flex items-start gap-2">
                        <span
                          className="mt-2 size-1.5 shrink-0 rounded-onboarding-pill bg-onboarding-purple-500"
                          aria-hidden
                        />
                        {item}
                      </li>
                    ))}
                  </ul>
                </div>
                <div className="border-t border-onboarding-purple-100 px-5 py-3 dark:border-onboarding-neutral-750">
                  <span className="inline-flex items-center gap-1.5 rounded-onboarding-pill bg-onboarding-purple-50 px-3 py-1 text-xs font-semibold text-onboarding-purple-600 dark:bg-onboarding-purple-900 dark:text-onboarding-purple-200">
                    <Sparkles className="size-3" aria-hidden />
                    {option.tag}
                  </span>
                </div>
              </button>
            );
          })}
        </div>
      </main>

      <CampaignTypeActions
        canContinue={Boolean(selectedType && orgId && !isLoading)}
        isSaving={isSaving}
        onBack={() => router.push(strategyHref("channels"))}
        onContinue={() => void handleContinue()}
      />
    </div>
  );
}
