"use client";

import {
  ArrowLeft,
  ArrowRight,
  BarChart3,
  Check,
  CirclePlay,
  Sparkles,
  TrendingUp,
  Upload,
  UserPlus,
} from "lucide-react";
import { useEffect, useLayoutEffect, useState } from "react";
import { ChoiceCard } from "@/components/onboarding/ChoiceCard";
import { Review } from "@/components/onboarding/Review";
import { OnboardingChrome } from "@/components/onboarding/OnboardingChrome";
import { ActionBar } from "@/components/ui/ActionBar";
import { Alert } from "@/components/ui/Alert";
import { Button } from "@/components/ui/Button";
import { PageHeader } from "@/components/ui/PageHeader";
import { applyStoredTheme } from "@/hooks/useThemeMode";
import { apiFetch, bootstrapCurrentOrganization } from "@/lib/api";
import {
  onboardingHref,
  navigateOnboarding,
  strategyHref,
} from "./steps";

const CAMPAIGN_TYPE_OPTIONS = [
  {
    id: "personalized_outreach",
    title: "Personalized Outreach",
    description: "AI videos personalized for each prospect.",
    bestFor: [
      "Lead generation",
      "Direct conversations",
      "Highest conversion potential",
    ],
    tag: "Generated by AI",
    icon: UserPlus,
  },
  {
    id: "ai_video_ad",
    title: "AI Campaign Video",
    description: "One AI-generated video delivered to your selected prospects.",
    bestFor: ["Awareness", "Traffic", "Lead generation at scale"],
    tag: "Generated by AI",
    icon: CirclePlay,
  },
  {
    id: "uploaded_video",
    title: "Uploaded Video Campaign",
    description: "Use your own video across your campaigns.",
    bestFor: ["Existing content", "Brand consistency", "Faster launch"],
    tag: "Upload • Studio",
    icon: Upload,
  },
] as const;

const VIDEO_ADVANTAGE_STATS = [
  { value: "Engage", label: "Capture attention", icon: TrendingUp },
  { value: "Connect", label: "Start conversations", icon: BarChart3 },
  { value: "Scale", label: "Choose the right format", icon: CirclePlay },
] as const;

type CampaignGoal = (typeof CAMPAIGN_TYPE_OPTIONS)[number]["id"];

type StrategyResponse = {
  id: string;
  orgId: string;
  campaignType: CampaignGoal | null;
};

export default function CampaignGoal() {
  useLayoutEffect(() => {
    applyStoredTheme();
  }, []);

  const [orgId, setOrgId] = useState<string | null>(null);
  const [selectedType, setSelectedType] = useState<CampaignGoal | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [loadAttempt, setLoadAttempt] = useState(0);

  useEffect(() => {
    let cancelled = false;

    async function loadStrategy() {
      setIsLoading(true);
      setError(null);
      try {
        const bootstrap = await bootstrapCurrentOrganization();
        if (cancelled) return;

        setOrgId(bootstrap.orgId);
        const strategy = await apiFetch<StrategyResponse>(
          `/strategy/${bootstrap.orgId}`,
        );
        if (cancelled) return;

        setSelectedType(strategy.campaignType);
      } catch (loadError) {
        if (!cancelled) {
          setError(
            loadError instanceof Error
              ? loadError.message
              : "Unable to load your campaign settings.",
          );
        }
      } finally {
        if (!cancelled) {
          setIsLoading(false);
        }
      }
    }

    void loadStrategy();
    return () => {
      cancelled = true;
    };
  }, [loadAttempt]);

  async function handleContinue() {
    if (!selectedType || !orgId || isSaving) {
      return;
    }

    setIsSaving(true);
    setError(null);
    try {
      await apiFetch<StrategyResponse>(`/strategy/${orgId}/campaign-type`, {
        method: "PATCH",
        body: JSON.stringify({ campaignType: selectedType }),
      });
      navigateOnboarding(onboardingHref("video-decision"));
    } catch (saveError) {
      setError(
        saveError instanceof Error
          ? saveError.message
          : "Unable to save your campaign type.",
      );
    } finally {
      setIsSaving(false);
    }
  }

  return (
    <div className="onboarding-page relative flex min-h-dvh w-full flex-col">
      <OnboardingChrome activeStep="campaign-type" />

      <main className="mx-auto flex w-full max-w-6xl flex-1 flex-col justify-center px-5 pt-40 pb-44 h-compact:justify-start h-compact:pt-36 lg:pt-34 lg:pb-28">
        <PageHeader
          className="mx-auto"
          icon={<Sparkles className="size-7" aria-hidden />}
          eyebrow="Campaign brief"
          title="Choose your campaign type"
          description="We&apos;ll recommend the best content, channels, and strategy based on your selection."
        />

        {error ? (
          <Alert
            tone="error"
            className="mx-auto mt-6 w-full max-w-4xl"
            action={!isSaving ? <Button type="button" variant="secondary" size="sm" onClick={() => setLoadAttempt((attempt) => attempt + 1)}>Try again</Button> : null}
          >
            {error}
          </Alert>
        ) : null}

        <Review
          className="mx-auto mt-8 w-full max-w-5xl"
          icon={<Sparkles className="size-6" strokeWidth={1.75} aria-hidden />}
          title="Video advantage"
          description="Video helps capture attention, increase engagement, and improve campaign performance."
        >
          <div className="flex flex-col gap-6 lg:flex-row lg:items-center">
            <div className="grid grid-cols-3 divide-x divide-onboarding-neutral-150 border-t border-onboarding-neutral-150 pt-5 dark:divide-onboarding-neutral-750 dark:border-onboarding-neutral-750 lg:border-t-0 lg:pt-0">
              {VIDEO_ADVANTAGE_STATS.map((stat) => {
                const Icon = stat.icon;
                return (
                  <div
                    key={stat.label}
                    className="min-w-0 px-3 text-center first:pl-0 last:pr-0 sm:px-5 lg:text-left"
                  >
                    <div className="flex items-center justify-center gap-1.5 lg:justify-start">
                      <Icon className="size-4 text-onboarding-purple-500" aria-hidden />
                      <p className="text-xl font-bold text-onboarding-purple-600 dark:text-onboarding-purple-200">
                        {stat.value}
                      </p>
                    </div>
                    <p className="mt-1 text-xs leading-snug text-onboarding-neutral-500 dark:text-onboarding-neutral-400">
                      {stat.label}
                    </p>
                  </div>
                );
              })}
            </div>
          </div>
        </Review>

        <div className="mx-auto mt-6 grid w-full max-w-5xl gap-4 md:grid-cols-3">
          {CAMPAIGN_TYPE_OPTIONS.map((option) => {
            const Icon = option.icon;
            const isSelected = selectedType === option.id;

            return (
              <ChoiceCard
                key={option.id}
                onClick={() => setSelectedType(option.id)}
                selected={isSelected}
                className="min-h-80 flex-col"
              >
                <div className="flex flex-1 flex-col px-6 pb-6 pt-7">
                  <span className="inline-flex items-center justify-center text-onboarding-purple-600 dark:text-onboarding-purple-200">
                    <Icon className="size-7" strokeWidth={1.75} aria-hidden />
                  </span>
                  <h2 className="mt-5 text-lg font-bold text-onboarding-ink dark:text-onboarding-neutral-0">
                    {option.title}
                  </h2>
                  <p className="mt-2 text-sm leading-6 text-onboarding-neutral-600 dark:text-onboarding-neutral-400">
                    {option.description}
                  </p>
                  <p className="mt-6 text-xs font-semibold tracking-wide text-onboarding-neutral-500 uppercase">
                    Best for
                  </p>
                  <ul className="mt-2.5 space-y-2 text-sm text-onboarding-neutral-700 dark:text-onboarding-neutral-300">
                    {option.bestFor.map((item) => (
                      <li key={item} className="flex items-start gap-2">
                        <span
                          className="mt-0.5 inline-flex size-4 shrink-0 items-center justify-center rounded-onboarding-pill bg-onboarding-purple-500 text-white"
                          aria-hidden
                        >
                          <Check className="size-2.5 stroke-[3]" />
                        </span>
                        {item}
                      </li>
                    ))}
                  </ul>
                </div>
                <div className="border-t border-onboarding-purple-100 bg-onboarding-purple-50/70 px-6 py-4 dark:border-onboarding-neutral-750 dark:bg-onboarding-purple-900/20">
                  <span className="inline-flex items-center gap-2 text-sm font-semibold text-onboarding-purple-600 dark:text-onboarding-purple-200">
                    <Sparkles className="size-3" aria-hidden />
                    {option.tag}
                  </span>
                </div>
              </ChoiceCard>
            );
          })}
        </div>
      </main>

      <ActionBar
        leading={
          <Button type="button" variant="secondary" onClick={() => navigateOnboarding(strategyHref("channels"))} className="h-13 px-7 text-base">
            <ArrowLeft className="size-5" aria-hidden />
            Back
          </Button>
        }
        trailing={
          <Button type="button" variant="primary" disabled={!selectedType || !orgId || isLoading || isSaving} onClick={() => void handleContinue()} className="h-13 px-8 text-base sm:px-10">
            {isSaving ? "Saving..." : "Continue to next step"}
            <ArrowRight className="size-5" aria-hidden />
          </Button>
        }
      />
    </div>
  );
}
